Add new kernel allocator
badgeteam/BadgerOS pull request #64
Opened 2024-03-26 01:10 UTC by hpvb

This should be a drop-in replacement for the previous allocator, it is ready to support user-space allocations and such.

This PR only replaces the old allocator with the new one, if this is merged I'll add the features to allocate user pages and protections.

This allocator was tested running vim, 3D programs, etc on Linux and seems to be quite solid. You can use the "build.sh" in kernel/src/malloc to produce a malloc.so which can be LD_PRELOAD'ed to validate the correctness of the allocator

2024-03-26 13:10 UTC, robotman2412 requested changes

2024-03-26 13:10 UTC, robotman2412 commented on kernel/src/malloc/slab-alloc.c
> +        // False positive from clang-tidy. ffs32 cannot return "32" despite its protestations
This doesn't seem to satisfy clang-tidy.
Consider adding a modulo operator in `bitmap_clear_bit` or use `// NOLINTNEXTLINE`.

2024-03-27 00:14 UTC, hpvb commented on kernel/src/malloc/slab-alloc.c
> +        // False positive from clang-tidy. ffs32 cannot return "32" despite its protestations
fixed

2024-03-27 01:29 UTC, robotman2412 approved these changes

2024-03-27 01:32 UTC, robotman2412 requested changes
Oh nvm kernel panics :c

2024-03-27 02:49 UTC, hpvb commented
I fixed the problem, turns out clang-tidy was correct about the SOFTBIT case. I was just assuming my original ffs32 and ffs64 implementations were equivalent to the __builtin_* equivalents. now they really are. *shame*

2024-03-27 14:01 UTC, robotman2412 approved these changes
It works now! Turn off the debug logs and merge it.

2024-03-28 12:45 UTC, merged